# Generated by Django 5.1.3 on 2024-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='propina',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_con_propina',
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
