# Generated by Django 5.1.3 on 2024-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_venta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='propina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
